config/routes.rb
SampleApp::Application.routes.draw do
  
  resources :users
  resources :sessions , :only => [:new,:create,:destroy]
  get "users/new"
  get "sessions/new"
  
  match 'signup',:to => 'users#new'
  match 'contacto',:to => 'paginas#contacto'
  match 'about',:to => 'paginas#about'
  match 'ayuda',:to => 'paginas#ayuda'
  match 'signin', :to => 'sessions#new'
  match 'signout', :to => 'sessions#destroy'
  root :to => 'paginas#home'
  

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime        not null
#  updated_at         :datetime        not null
#  encrypted_password :string(255)
#  salt               :string(255)
#
class User < ActiveRecord::Base
  require 'digest'
  attr_accessor :password
  attr_accessible :email, :name ,:password ,:password_confirmation
  
  
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name , :presence => true , 
  :length => { :maximum => 50 }
                    
  validates :email, :presence => true ,
  :format => { :with => email_regex },
  :uniqueness => {:case_sensitive => false}
  validates :password , :confirmation => true,
                        :presence => true,
                        :length => { :within => 6..40 }
                        
                        
  #usando el metodo callback para la implementacion antes de grabar
  
  before_save :encrypt_password
  
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  def self.authenticate(email,submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submited_password)
  end
   ##desde aki los metodos privados###########################3 
  private
  
  def encrypt_password
    self.salt = make_salt if new_record?
    self.encrypted_password = encrypt(self.password)
  end
  
  def encrypt(string)
    secure_hash("#{salt}--#{string}")
  end
  
  def make_salt
    secure_hash("#{Time.now.utc}--#{password}")
  end
  
  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end
    
                     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/paginas_controller.rb
class PaginasController < ApplicationController
  def home
  @titulo = "Home" 
  end

  def contacto
  @titulo = "Contacto"
  end
  
  def about
  @titulo = "About"
  end
  def ayuda
    @titulo = "Ayuda"
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new 
  @title = "Sign in"
  end
  
  def create
    render 'new'
  end
  
  def destroy
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  @titulo = "Sign up"
  @user = User.new
  end
  def show 
    @user = User.find(params[:id])
    @titulo=@user.name
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      @titulo= "Sign up"
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
#regresa un titulo en caso de que no exista 
def titulo 
  base_titulo="Aplicaciones Rapidas con Rails"
    if @titulo.nil?
    base_titulo
    else
    "#{base_titulo} | #{@titulo}"
    end
  end 
  def logo
  logo=image_tag("logo.png",:alt => "Sample App", :class => "round")
  end   
end

app/helpers/paginas_helper.rb
module PaginasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user,options = { :size => 70 })
   gravatar_image_tag(user.email.downcase, :alt => user.name,
                                            :class => 'gravatar',
                                            :gravatar => options )
  end
  
end

app/views/layouts/_footer.html.erb
<nav class="btn-group">
<%= link_to "About", about_path,:class => 'btn' %></li>
<%= link_to "Contacto", contacto_path , :class => 'btn' %>
<%= link_to "Ayuda", ayuda_path , :class => 'btn' %>

</nav>

app/views/layouts/_header.html.erb
	<header>
			<%= link_to logo,root_path %>
		
		<nav>
			<div class="navbar">
  				<div class="navbar-inner">
   					 <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
     					<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        					<span class="icon-bar"></span>
        					<span class="icon-bar"></span>
        					<span class="icon-bar"></span>
      					</a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <a class="brand" href="#">Sample App</a>
		<ul class="nav">
       			<li class="active"></li>
        		<li><%= link_to "Home", root_path %></li>
        		<li><%= link_to "Ayuda",ayuda_path %></li>
        		<li><%= link_to "Sing Up",signup_path %></li>
		</ul>
    <div class="nav-collapse"></div>
 
    				</div>
  			</div>
		</div>
 </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if It IE 9]>
<%= javascript_include_tag "http://html5shiv.googlecode.com/svn/trunk/html5.js"%>	
<![endif]-->	
<%= stylesheet_link_tag 'application', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= titulo %></title>
<%= csrf_meta_tag %>
<%= render 'layouts/stylesheets' %>
</head>
<body>
<div class="container">
	<%= render 'layouts/header'%>
<section>
	<% flash.each do |key, value| %>
	<h1><div class="flash <%= key %>"><%= value %></div></h1>
	<% end %>

	<%= yield %>
</section>
<footer>
	<%= render 'layouts/footer'%>
	<%= debug(params) if Rails.env.development? %>
</footer>
</div>
</body>
</html>

app/views/paginas/about.html.erb
<h1>About Us</h1>
<p>
<a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
is a project to make a book and screencasts to teach web development
with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
is the sample application for the tutorial.
</p>

app/views/paginas/ayuda.html.erb
<h1>Ayuda</h1>
<p>
<a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
is a project to make a book and screencasts to teach web development
with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
is the sample application for the tutorial.
</p>

app/views/paginas/contacto.html.erb
<h1>Contact</h1>
<p>
Contact Ruby on Rails Tutorial about the sample app at the
<a href="http://railstutorial.org/feedback">feedback page</a>.
</p>

app/views/paginas/home.html.erb
<h1>Sample App</h1>
<p>
This is the home page for the
<a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
sample application.
</p>
<%= link_to "Inicia Sesion" , "#", :class => "btn btn-inverse"%>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@user.errors.count, "errores") %>
		 al intentar grabar al usuario:</h2>
		<p>El problema esta en los siguientes campos:</p>
		<ul>
		<% @user.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/users/new.html.erb
<h1>Registrate !</h1>
	
	<%= form_for @user, :class => "form-horizontal" do |f| %>
	<%=render 'shared/error_messages'%>
	<div class="control-group">
		<%= f.label :name ,  :class => "control-label"  %>
		 <div class="controls">
		<%= f.text_field :name ,  :class => "input-xlarge"  %>
		</div>
		<%= f.label :email ,  :class => "control-label"  %>
		<div class="controls">
		<%= f.text_field :email ,  :class => "input-xlarge"  %>	
		</div>
		<%= f.label :password ,  :class => "control-label"  %>
		<div class="controls">
		<%= f.password_field :password ,  :class => "input-xlarge"  %>	
		</div>
		<%= f.label :password_confirmation ,"Cofirmacion", :class => "control-label"  %>
		<div class="controls">
		<%= f.password_field :password_confirmation , :class => "input-xlarge"  %>	
		</div>
		<div class="controls">
			<%= f.submit "Registro!" , :class => 'btn btn-danger' %>
		</div>
		
	</div>
	<% end %>

app/views/users/show.html.erb
<table class="table table-striped">
 <tr>
 	<td>
		<h1>
			<%= gravatar_for @user %>
			<%= @user.name %>
		</h1>
	</td>
	<td>
		<strong>Nombre</strong> <%= @user.name %><br />
		<strong>URL</strong> <%= link_to user_path(@user),@user%><br />
	</td>
 </tr>
</table>